copy .\ribgen\meshRibgen.dll %RATTREE%\lib\plugins
copy .\ribgen\meshRibgen.slim %RATTREE%\lib\plugins
copy .\procedural\meshCacheProcedural.dll %RATTREE%\lib\plugins
copy .\slim\ace.slim %RATTREE%\lib\slim
copy .\slim\displacement_z.slim %RATTREE%\lib\slim
copy .\slim\eye.slim %RATTREE%\lib\slim
copy .\slim\fur.slim %RATTREE%\lib\slim
copy .\slim\light_z.slim %RATTREE%\lib\slim
copy .\slim\ylset.slim %RATTREE%\lib\slim
copy .\slim\z_colors_prt.slim %RATTREE%\lib\slim
copy .\slim\z_lights_hdr.slim %RATTREE%\lib\slim
copy .\slim\include\zprt.dll %RATTREE%\lib\slim\include
copy .\slim\include\zprt.dll %RMANTREE%\lib\shaders
copy TOR.ini %RATTREE%\etc
copy slim.ini %RATTREE%\etc