copy .\ribgen\fishGen.dll D:\wamp\www\ztools\ribgen
copy .\ribgen\fishGen.slim D:\wamp\www\ztools\ribgen
copy .\ribgen\meshRibgen.dll D:\wamp\www\ztools\ribgen
copy .\ribgen\meshRibgen.slim D:\wamp\www\ztools\ribgen
copy .\ribgen\hairRibgen.dll D:\wamp\www\ztools\ribgen
copy .\ribgen\hairRibgen.slim D:\wamp\www\ztools\ribgen
copy .\procedural\meshCacheProcedural.dll D:\wamp\www\ztools\procedural
copy .\procedural\fishProcedural.dll D:\wamp\www\ztools\procedural
copy .\procedural\zhairProcedural.dll D:\wamp\www\ztools\procedural
copy .\slim\snow.slim D:\wamp\www\ztools\slim
copy .\slim\ace.slim D:\wamp\www\ztools\slim
copy .\slim\displacement_z.slim D:\wamp\www\ztools\slim
copy .\slim\eye.slim D:\wamp\www\ztools\slim
copy .\slim\fur.slim D:\wamp\www\ztools\slim
copy .\slim\light_z.slim D:\wamp\www\ztools\slim
copy .\slim\ylset.slim D:\wamp\www\ztools\slim
copy .\slim\z_colors_prt.slim D:\wamp\www\ztools\slim
copy .\slim\z_lights_hdr.slim D:\wamp\www\ztools\slim
copy .\slim\include\zprt.dll D:\wamp\www\ztools\slim\include
copy .\slim\include\zdump.dll D:\wamp\www\ztools\slim\include
copy .\plug-ins\meshCache.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\meshCache2008.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\HDREnvironmentViewer70.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\HDREnvironmentViewer2008.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\fishViz.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\ZHair2008.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\ZHair70.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\particleWrap2008.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\particleWrap70.mll D:\wamp\www\ztools\plug-ins
copy .\plug-ins\cameraFrustum70.mll D:\wamp\www\ztools\plug-ins
copy ..\cameraFrustum\cameraFrustumNode.py D:\wamp\www\ztools\plug-ins
copy .\plug-ins\ZDepthMap70.mll D:\wamp\www\ztools\plug-ins
copy TOR.ini D:\wamp\www\ztools
copy slim.ini D:\wamp\www\ztools
copy rat_install.bat D:\wamp\www\ztools
copy .\scripts\exrdepthMapMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\particleWrapMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\hdrviewerMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\vertexCacheMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\slimcontrolMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\mtorSetQuantize.mel D:\wamp\www\ztools\scripts
copy .\scripts\fishMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\exrSet2ndDisplay.mel D:\wamp\www\ztools\scripts
copy .\scripts\zhairMenus.mel D:\wamp\www\ztools\scripts
copy .\scripts\combCurveProperties.mel D:\wamp\www\ztools\scripts
copy .\scripts\combCurveValues.mel D:\wamp\www\ztools\scripts
copy .\scripts\cameraFrustumMenus.mel D:\wamp\www\ztools\scripts
copy .\application\prtServer.exe D:\wamp\www\ztools\application
copy .\application\laziPRT.exe D:\wamp\www\ztools\application
copy .\application\cheatPRT.bat D:\wamp\www\ztools\application
copy .\changeLog.txt D:\wamp\www\ztools