global proc
DL_userGetGeoTypeData(string $types[],
                      string $plugin_requirements[],
                      string $cache_commands[],
                      string $output_commands[])
{
  clear($types);
  clear($plugin_requirements);
  clear($cache_commands);
  clear($output_commands);

  $types[0] = "pmapViz";
  $plugin_requirements[0] = "ParticleMapRIBGenDL";
  $cache_commands[0] = "pmapVizCacheGeo";
  $output_commands[0] = "nil";
}
